ttsx/tt_user/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url('^register/$', views.register),
    url('^register_handle/$', views.register_handle),
    url('^register_valid/$', views.register_valid),
    url('^login/$', views.login),
    url('^login_handle/$', views.login_handle),
    url('^logout/$', views.logout),
    url('^$', views.center),
    url('^order/$', views.order),
    url('^site/$', views.site),
    url('^islogin/$', views.islogin),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('^user/',include('tt_user.urls')),
    url('^',include('tt_goods.urls')),
    url('^demo/',include('tt_demo.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url('^cart/',include('tt_cart.urls')),
    url('^order/',include('tt_order.urls')),
]

ttsx/tt_order/models.py
# coding=utf-8
from django.db import models


class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('tt_user.UserInfo')
    odate = models.DateTimeField(auto_now_add=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('tt_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

ttsx/tt_user/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    uname=models.CharField(max_length=20)
    upwd=models.CharField(max_length=40)
    uemail=models.CharField(max_length=40)

    ushou=models.CharField(max_length=10, default='')
    uaddress=models.CharField(max_length=100, default='')
    uphone=models.CharField(max_length=11, default='')

ttsx/tt_user/views.py
# coding=utf-8
from django.shortcuts import render, redirect
from hashlib import sha1
from django.http import JsonResponse
import datetime
from django.core.paginator import Paginator

from models import UserInfo
from user_decorators import user_login
from tt_goods.models import GoodsInfo
from tt_order.models import *


# Create your views here.
def register(request):
    context = {'title': '注册', 'top': '0'}
    return render(request, 'tt_user/register.html', context)


def register_handle(request):
    dict = request.POST
    uname = dict.get('user_name')
    upwd = dict.get('user_pwd')
    upwd2 = dict.get('cpwd')
    email = dict.get('user_email')

    if upwd != upwd2:
        return redirect('/user/register/')

    s1 = sha1()
    s1.update(upwd)
    upwd_sha1 = s1.hexdigest()

    user = UserInfo()
    user.uname = uname
    user.upwd = upwd_sha1
    user.uemail = email
    user.save()

    return redirect('/user/login/')


def register_valid(request):
    uname = request.GET.get('uname')
    result = UserInfo.objects.filter(uname=uname).count()
    context = {'valid': result}
    return JsonResponse(context)


def login(request):
    uname=request.COOKIES.get('uname')
    context = {'title': '登录', 'top': '0','uname':uname}
    return render(request, 'tt_user/login.html', context)


def login_handle(request):
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('user_pwd')
    uname_jz = post.get('name_jz', '0')

    s1 = sha1()
    s1.update(upwd)
    upwd_sha1 = s1.hexdigest()

    context = {'title': '登录', 'uname': uname, 'upwd': upwd, 'top': '0'}
    # 根据用户名查询数据，如果未查到返回[]，如果查到则返回[UserInfo]
    users = UserInfo.objects.filter(uname=uname)
    if len(users) == 0:
        # 用户名错误
        context['name_error'] = '1'
        return render(request, 'tt_user/login.html', context)
    else:
        if users[0].upwd == upwd_sha1:  # 登录成功
            # 记录当前登录的用户
            request.session['uid'] = users[0].id
            request.session['uname'] = uname
            # 重定向，即从哪儿来，回哪儿去
            path = request.session.get('url_path', '/')
            response = redirect(path)
            # 记住用户名
            if uname_jz == '1':
                response.set_cookie('uname', uname, expires=datetime.datetime.now() + datetime.timedelta(days=7))
            else:
                response.set_cookie('uname', '', max_age=-1)
            return response
        else:
            # 密码错误
            context['pwd_error'] = '1'
            return render(request, 'tt_user/login.html', context)


def logout(request):
    request.session.flush()
    return redirect('/user/login/')


def islogin(request):
    result = 0
    if request.session.has_key('uid'):
        result = 1
    return JsonResponse({'islogin': result})


@user_login
def center(request):
    user = UserInfo.objects.get(pk=request.session['uid'])
    #查询最近浏览商品
    goods_ids=request.COOKIES.get('goods_ids','').split(',')
    # goods_list=GoodsInfo.objects.filter(id__in=goods_ids)
    goods_list=[]
    for gid in goods_ids:
        if gid:
            goods_list.append(GoodsInfo.objects.get(id=gid))
    context = {'title': '用户中心', 'user': user,'goods_list':goods_list}
    return render(request, 'tt_user/center.html', context)
#在视图函数执行前进行判断，如果登录则继续执行视图函数，如果未登录则转向到登录视图


@user_login
def order(request):
    uid=request.session.get('uid')
    order_list=OrderInfo.objects.filter(user_id=uid).order_by('-odate')

    pindex=int(request.GET.get('page','1'))
    paginator=Paginator(order_list,2)
    if pindex<=0:
        pindex=1
    if pindex>=paginator.num_pages:
        pindex=paginator.num_pages
    page=paginator.page(pindex)

    context = {'title': '用户订单','page':page}
    return render(request, 'tt_user/order.html', context)


@user_login
def site(request):
    user = UserInfo.objects.get(pk=request.session['uid'])
    if request.method == 'POST':
        post = request.POST
        user.ushou = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.uphone = post.get('uphone')
        user.save()
    context = {'title': '收货地址', 'user': user}
    return render(request, 'tt_user/site.html', context)

'''
user.addressinfo_set.all

将当前地址进行判断，如果不是注册、登录等地址的话，则记录下来，当登录成功后，则转向此地址
解决方案：中间件
    process_view

'''

ttsx/templates/tt_user/cart.html
{%extends 'base.html'%}

{%block body%}


	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="/static/images/goods/goods012.jpg"></li>
		<li class="col03">奇异果<br><em>25.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="/static/images/goods/goods003.jpg"></li>
		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">16.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">16.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="place_order.html">去结算</a></li>
	</ul>

{%endblock body%}

ttsx/templates/tt_user/center.html
{%extends 'base.html'%}

{%block body%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
			<div class="info_con clearfix">
			<h3 class="common_title2">基本信息</h3>
					<ul class="user_info_list">
						<li><span>用户名：</span>{{user.uname}}</li>
						<li><span>电子邮箱：</span>{{user.uemail}}</li>
					</ul>
			</div>

			<h3 class="common_title2">最近浏览</h3>
			<div class="has_view_list">
				<ul class="goods_type_list clearfix">
					{%for goods in goods_list%}
					<li>
						<a href="/{{goods.id}}/"><img src="/static/{{goods.gpic}}"></a>
						<h4><a href="/{{goods.id}}/">{{goods.gtitle}}</a></h4>
						<div class="operate">
							<span class="prize">￥{{goods.gprice}}</span>
							<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
							<a href="#" class="add_goods" title="加入购物车"></a>
						</div>
					</li>
					{%endfor%}
				</ul>
			</div>
		</div>
	</div>
{%endblock body%}

ttsx/templates/tt_user/login.html
{%extends 'base.html'%}

{%block script%}
<script>
	name_ok=true;
	pwd_ok=true;
	$(function () {
		$('.name_input').blur(function () {
			uname=$(this).val();
			if(uname.length<5||uname.length>20)
			{
				$('.user_error').html('请输入5-20个字符的用户名').show();
				name_ok = false;
			}else{
				$('.user_error').html('').hide();
				name_ok = true;
			}
        });

		$('.pass_input').blur(function () {
			upwd=$(this).val();
			if(upwd.length<8||upwd.length>20)
			{
				$('.pwd_error').html('密码最少8位，最长20位').show();
				pwd_ok = false;
			}else{
				$('.pwd_error').html('').hide();
				pwd_ok = true;
			}
        });

		$('form').submit(function () {
			$('.name_input').blur();
			$('.pass_input').blur();
			return name_ok && pwd_ok;
        });

		if('{{name_error}}'=='1'){
			$('.user_error').html('用户名错误').show();
			name_ok = false;
		}
		if('{{pwd_error}}'=='1'){
			$('.pwd_error').html('密码错误').show();
			pwd_ok = false;
		}
    });
</script>
{%endblock script%}

{%block body%}

	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="/user/login_handle/">
						{%csrf_token%}
						<input type="text" name="user_name" value="{{uname}}" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="user_pwd" value="{{upwd}}" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="name_jz" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{%endblock body%}

ttsx/templates/tt_user/order.html
{%extends 'base.html'%}

{% block script %}
<script>
$(function () {
    $('.col04').each(function () {
        var count=parseInt($(this).prev().text());
        var price=parseFloat($(this).prev().prev().find('span').text());
        var total=count*price;
        $(this).text(total.toFixed(2)+'元');
    });
});
</script>
{% endblock script %}

{%block body%}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="/user/">· 个人信息</a></li>
            <li><a href="/user/order/" class="active">· 全部订单</a></li>
            <li><a href="/user/site/">· 收货地址</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>

{% for order in page %}
<ul class="order_list_th w978 clearfix">
    <li class="col01">{{ order.odate }}</li>
    <li class="col02">订单号：{{ order.oid }}</li>
    <li class="col02 stress">{% if order.oIsPay == True %}已支付{% else %}未支付{% endif %}</li>
</ul>

<table class="order_list_table w980">
    <tbody>
        <tr>
            <td width="55%">
                {% for detail in order.orderdetailinfo_set.all %}
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="/static/{{ detail.goods.gpic }}"></li>
                    <li class="col02">{{ detail.goods.gtitle|truncatechars:18 }}<em><span>{{ detail.price }}</span>元/
                        {{ detail.goods.gunit }}</em></li>
                    <li class="col03">{{ detail.count }}</li>
                    <li class="col04">11.80元</li>
                </ul>
                {% endfor %}
            </td>
            <td width="15%">{{ order.ototal }}元</td>
        {% if order.oIsPay %}
            <td width="15%">已付款</td>
            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
        {% else %}
            <td width="15%">待付款</td>
            <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
        {% endif %}
        </tr>
    </tbody>
</table>
{% endfor %}

    <div class="pagenation">
        {% if page.has_previous %}
            <a href="?page=1">首页</a>
            <a href="?page={{ page.number|add:-1 }}">上一页</a>
        {% endif %}
{% load filters %}
        {% for pindex in page|page_list %}
            {% if pindex == page.number %}
            <a href="#" class="active">{{ pindex }}</a>
            {% else %}
            <a href="?page={{ pindex }}">{{ pindex }}</a>
            {% endif %}
        {% endfor %}

        {% if page.has_next %}
            <a href="?page={{ page.number|add:1 }}">下一页</a>
            <a href="?&page={{ page.paginator.num_pages }}">末页</a>
        {% endif %}
    </div>

    </div>
</div>
{%endblock body%}

ttsx/templates/tt_user/place_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-提交订单</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="site.html" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		<ul class="goods_list_td clearfix">
			<li class="col01">1</li>			
			<li class="col02"><img src="images/goods/goods012.jpg"></li>
			<li class="col03">奇异果</li>
			<li class="col04">500g</li>
			<li class="col05">25.80元</li>
			<li class="col06">1</li>
			<li class="col07">25.80元</li>	
		</ul>
		<ul class="goods_list_td clearfix">
			<li class="col01">2</li>			
			<li class="col02"><img src="images/goods/goods003.jpg"></li>
			<li class="col03">大兴大棚草莓</li>
			<li class="col04">500g</li>
			<li class="col05">16.80元</li>
			<li class="col06">1</li>
			<li class="col07">16.80元</li>	
		</ul>
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>42.60元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>52.60元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>	

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="js/jquery-1.12.2.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = 'index.html';
					});	
				},3000)
				
			});
		});
	</script>
</body>
</html>

ttsx/templates/tt_user/register.html
{%extends 'base.html'%}

{%block script%}
<script type="text/javascript" src="/static/js/register.js"></script>
{%endblock script%}

{%block body%}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/user/register_handle/" id="reg_form">
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="user_pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="user_email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>
		</div>
	</div>
{%endblock body%}

ttsx/templates/tt_user/site.html
{%extends 'base.html'%}

{%block body%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uaddress}} （{{user.ushou}} 收） {{user.uphone}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="/user/site/">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress"></textarea>
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone">
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{%endblock body%}